[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:vnc]
command=/usr/bin/vncserver -localhost no :1 -geometry 1920x1080 -depth 24
autostart=true
autorestart=true

[program:novnc]
command=/usr/bin/websockify -D --web=/usr/share/novnc 8080 localhost:5901
autostart=true
autorestart=true

[program:xrdp]
command=/usr/sbin/xrdp --nodaemon
autostart=true
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:file-server]
command=/usr/bin/python3 /setup.py
autostart=true
autorestart=true